/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vass.di.quiz.certification.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the responseUser service. Represents a row in the &quot;QUIZ_responseUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.vass.di.quiz.certification.data.model.impl.responseUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.vass.di.quiz.certification.data.model.impl.responseUserImpl</code>.
 * </p>
 *
 * @author dgarces
 * @see responseUser
 * @generated
 */
@ProviderType
public interface responseUserModel extends BaseModel<responseUser> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a response user model instance should use the {@link responseUser} interface instead.
	 */

	/**
	 * Returns the primary key of this response user.
	 *
	 * @return the primary key of this response user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this response user.
	 *
	 * @param primaryKey the primary key of this response user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this response user.
	 *
	 * @return the uuid of this response user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this response user.
	 *
	 * @param uuid the uuid of this response user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the response user ID of this response user.
	 *
	 * @return the response user ID of this response user
	 */
	public long getResponseUserId();

	/**
	 * Sets the response user ID of this response user.
	 *
	 * @param responseUserId the response user ID of this response user
	 */
	public void setResponseUserId(long responseUserId);

	/**
	 * Returns the response user uuid of this response user.
	 *
	 * @return the response user uuid of this response user
	 */
	public String getResponseUserUuid();

	/**
	 * Sets the response user uuid of this response user.
	 *
	 * @param responseUserUuid the response user uuid of this response user
	 */
	public void setResponseUserUuid(String responseUserUuid);

	/**
	 * Returns the user ID of this response user.
	 *
	 * @return the user ID of this response user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this response user.
	 *
	 * @param userId the user ID of this response user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this response user.
	 *
	 * @return the user uuid of this response user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this response user.
	 *
	 * @param userUuid the user uuid of this response user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the question ID of this response user.
	 *
	 * @return the question ID of this response user
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this response user.
	 *
	 * @param questionId the question ID of this response user
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the answer ID of this response user.
	 *
	 * @return the answer ID of this response user
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this response user.
	 *
	 * @param answerId the answer ID of this response user
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the create date of this response user.
	 *
	 * @return the create date of this response user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this response user.
	 *
	 * @param createDate the create date of this response user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this response user.
	 *
	 * @return the modified date of this response user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this response user.
	 *
	 * @param modifiedDate the modified date of this response user
	 */
	public void setModifiedDate(Date modifiedDate);

}